name: distance_loss
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.7.12
  - pytorch::pytorch=1.11.0
  - pytorch::torchaudio=0.11.0
  - pytorch::torchvision=0.12.0
  - pip:
    - pytorch_lightning==1.7.7
    - wandb==0.13.10
    - pycocotools==2.0.6
    - python-box==7.0.0
    - segmentation_models_pytorch==0.3.2
    - albumentations==1.3.0
    - Pillow==9.5.0
    - scipy==1.7.3
    - matplotlib==3.5.1
    - pandas==1.3.5
    - kaggle==1.5.16