# 1 A100 GPU 80 GB VRAM
accelerator: auto # gpu, tpu, cpu, auto
device_num: 1 # Number of gpu, check if T4 vs P100
precision: 16 # Double precision (64), full precision (32), half precision (16) or bfloat16 precision (bf16)