defaults:
  - dataset: cityscapes
  - server: kaggle_T4

exp:
  wandb_proj: start-up-project
  name: A100_512_512_DIST_FIX_APPX_DIFF_SEED
  model: Unet # DeepLabV3Plus, UnetPlusPlus, Unet, FPN
  encoder: resnet50 # mobilenet_v2, efficientnet-b5, resnet34, mit_b1 
  loss: dist_transform # dist_transform, bce, iou, dice, dice&bce, dice&focal
  deterministic: true # for reproducibity. If True, sets whether PyTorch operations must use deterministic algorithms. Set to "warn" to use deterministic algorithms whenever possible. "warn" for DeepLabV3Plus.     
  SEED: 42

trainer:
  max_epoch: 100
  max_time: 00:11:55:00
  lr: 0.0003 # 0.001, 0.0003
  reduce_rl_on: false
  patience: 20 # for validation loss
  
checkpoint:
  motior: val_per_image_bIoU
  save_dir: ./logs/lightning_logs/checkpoints/
  resume_dir: model.ckpt

vis:
  img_num: 8
  val_batch_id: 5
  dir: ./models/cityscapes_dist_transform_unet_r50_1024
