name: CelebAMask-HQ
dir: ./data/CelebAMask-HQ-v2/
output_class_num: 1
mode: binary
transform:
  image_resize_h: 512 # 576
  image_resize_w: 512 # 800
train_dl_batchsize: 128
val_dl_batchsize: 128
test_dl_batchsize: 128